spring.application.name=calcio


spring.datasource.url=jdbc:postgresql://localhost:5432/calcio
spring.datasource.username=postgres
spring.datasource.password=siw1
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.content-type=text/html
#==================================
# = Messages configuration
#==================================
spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8
#==================================
# = Logging configuration
#==================================
logging.level.root=INFO
logging.level.it.uniroma3.siw.movie.controller.MovieController==DEBUG

#==================================
# = OAuth2 Login Configuration
#==================================
# NOTA SICUREZZA: il file delle chiavi è un file .gitignore 
# La riga qui sotto dice a Spring di caricare anche quel file.
spring.profiles.include=secrets